robots:
  go2:
    package: go2_description
    model: mjcf/go2.xml
    nodes: 
      normal: Go2SimNode
      ground_truth: Go2SimGroundTruth
  pendulum:
    package: pendulum_description
    model: mjcf/pendulum.xml
    nodes: 
      normal: PendulumSimNode
      ground_truth: PendulumSimGroundTruth

scenes:
  flat_ground:
    package: scene_description
    model: mjcf/flat_ground.xml
  # rough_ground:
  #   package: terrain_description
  #   model: mjcf/rough_ground.xml